### PR TITLE
[MRG] API: remove num_labeled parameter

### LINKED ISSUE #118: Do we need the num_labeled parameter for *_Supervised classes?
#### Description

The *_Supervised classes allow to use a weakly supervised algorithm on labeled data by creating constraints from the labeled points.

I do not really understand why these classes have a parameter `num_labeled`, which is used to ignore some labeled points when creating constraints. To reduce the training complexity, it is enough to limit the number of constraints by using the `num_constraints` parameter. Using all available points to create the desired number of constraints can only benefit the algorithm as it sees more different points in the training constraints (i.e., it reduces variance).

I think `num_labeled` could be removed so that all available points are used to create the desired number of constraints.

### PR DESCRIPTION
**Pull request by wdevazelhes**
Fixes #118

### CODE REVIEW

**Comment by terrytangyuan** [comment]
We should probably record these kind of breaking changes in a change log?

**Comment by bellet** [comment]
I think the _Supervised classes are introduced in this next 0.4.0 release though?

**Comment by bellet** [comment]
My mistake it looks like they were introduced in 0.3.0 (albeit without doc)...
Then, maybe we can release 0.4.0 without this and save this PR for 0.5.0 (along with major API changes)?

**Comment by wdevazelhes** [comment]
Yes I think so, I tried to resolve the conflicts but my branch was not updated so I messed it up :p I will try again...

**Comment by terrytangyuan** [comment]
Seems like rebase was done incorrectly/unsuccessfully? At least from a quick glance it seems like `setup.py`'s changes are unexpected.

**Comment by wdevazelhes** [comment]
Yes indeed, I think I did a bad revert, I'll revert try revert the revert d6bd0d4

**Comment by wdevazelhes** [comment]
OK now there's just some tests for NCA that I don't understand why they are here...

**Comment by wdevazelhes** [comment]
Oups, it appears I deleted it in the big merge #139  (cf. https://github.com/metric-learn/metric-learn/commit/23d07466961fa7a72aa8692bc42d6d569b80c5c9#diff-1d435b5cb210c40bb6a7261667f5c5acL138)
I'll open an issue to put it back, so that it should disappear of the diff of this PR as soon as it is merged

**Comment by wdevazelhes** [comment]
Here is the PR that we should merge (as soon as tests passes): #143

**Comment by wdevazelhes** [comment]
there just remains one error of version to update and it should be OK

**Comment by wdevazelhes** [comment]
I guess this PR should be ready to merge now, as soon as tests pass

**Comment by bellet** [comment]
still 1 failure ;-)

**Comment by wdevazelhes** [comment]
Turns out I used the function `Constraint.random_subset` in #139 so I'll just need change those lines

**Comment by wdevazelhes** [comment]
It should be good to merge now :p

**Pull request merged**
