### PR TITLE
Test pr coverage

### PR DESCRIPTION
**Pull request by wdevazelhes**
This test tests that if we decrease too much the test coverage in a PR some error will be shown

### CODE REVIEW

**Comment by wdevazelhes** [comment]
OK so it seems that no warning is shown...

**Comment by wdevazelhes** [comment]
OK now it's a bit better (codecov is in one of the CI checks) but still doesn't work (I just realized that I had put the wrong version in the test (3.6 instead of 3.4..., see commit https://github.com/metric-learn/metric-learn/commit/cd1861114889f59ed2a8d2290cae06c46b489601)

**Comment by wdevazelhes** [comment]
It works now !

**Comment by wdevazelhes** [comment]
Closing, since it's working. Maybe the comment is a bit annoying since we already have the CIs ? I can deactivate it from the .codecov.yml 
Tell me what you prefer

**Comment by terrytangyuan** [comment]
I think it's better to disable comments since it's too verbose IMO.

**Comment by bellet** [comment]
I agree. As long as we can easily check the codecov report it's fine

**Comment by wdevazelhes** [comment]
Agreed, done

**Pull request closed without merging**
