### PR TITLE
[MRG] Add test coverage

### LINKED ISSUE #170: Add test coverage badge
Running pytest coverage on the package returned 94%, which I believe is a pretty good score (but we'll do even better :) ) 
So I think it would be good to have the badge on the README page

### PR DESCRIPTION
**Pull request by wdevazelhes**
Fixes #170

This PR is an intent to add the code coverage badge and PR checks to metric-learn

### CODE REVIEW

**Comment by wdevazelhes** [comment]
The badge is working: see https://github.com/metric-learn/metric-learn/blob/43fd254fcd5025392ee9083bf04d6fc717c9f3e1/README.rst
I'll update the name of the branch in the badge so that when the PR is merged it will be the right branch (master)

**Comment by wdevazelhes** [comment]
Regarding the check that new PRs don't decrease the test coverage (see #170), I took the code from scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/a7e17117bb15eb3f51ebccc1bd53e42fcb4e6cd8/.codecov.yml

To see whether it works, I suggest we merge this PR, and we try to do a test PR deleting a lot of tests and see whether it raises an error

**Comment by perimosocordiae** [comment]
Looks good, merged. We can adjust settings as needed.

**Comment by bellet** [comment]
We could add the badge in the index page of the doc also?

For future PRs, how is this going to work? Will we be able to easily see the increase/decrease of test coverage induced by the proposed changes?

**Comment by bellet** [comment]
Also why do we see 96% in the link https://github.com/metric-learn/metric-learn/blob/43fd254fcd5025392ee9083bf04d6fc717c9f3e1/README.rst you provided, and 94% on the current README?

**Comment by bellet** [comment]
And finally :-) The link to files to see which lines are not covered do not work on codecov:
https://codecov.io/gh/metric-learn/metric-learn/tree/master/metric_learn
The website suggests a path setting issue, it would be nice to fix this

**Comment by bellet** [comment]
> And finally :-) The link to files to see which lines are not covered do not work on codecov:
> https://codecov.io/gh/metric-learn/metric-learn/tree/master/metric_learn
> The website suggests a path setting issue, it would be nice to fix this

Nevermind, seems to work now

**Comment by wdevazelhes** [comment]
> We could add the badge in the index page of the doc also?

Yes, done in commit https://github.com/metric-learn/metric-learn/commit/4e668d9ebed862987303de350ca62b70cbdb7ccb

> For future PRs, how is this going to work? Will we be able to easily see the increase/decrease of test coverage induced by the proposed changes?

Yes, it works now, see https://github.com/metric-learn/metric-learn/pull/183

**Comment by wdevazelhes** [comment]
> Also why do we see 96% in the link https://github.com/metric-learn/metric-learn/blob/43fd254fcd5025392ee9083bf04d6fc717c9f3e1/README.rst you provided, and 94% on the current README?

I am not sure, but looking into codecov's page at "commits" https://codecov.io/gh/metric-learn/metric-learn/commits, I think it's because the first commit that worked was with a new pytest version (installed now by default by the CI), that maybe didn't work the same as the one I put after (the current one: pytest==3.6)

**Pull request merged**
