### PR TITLE
[MRG] Documentation: introduction to metric learning

### PR DESCRIPTION
**Pull request by bellet**
This PR improves the documentation by adding a proper section introducing metric learning (problem setting, mahalanobis distance, use cases and general references). A small description of the package is also added to the index page for clarity.

### CODE REVIEW

**Comment by bellet** [comment]
I still need to write a few lines about use-cases.

Note that I also commented out the part listing the class methods: I think it would be better to move this to the supervised and weakly supervised sections, within a proper 'API' subsection

**Comment by bellet** [comment]
This should be ready to merge - feedback is welcome.

**Comment by wdevazelhes** [comment]
> Note that I also commented out the part listing the class methods: I think it would be better to move this to the supervised and weakly supervised sections, within a proper 'API' subsection

Yes I agree, the current 'Package overview' subsection is currently not organized. We could add these comment lines, plus also organize the sections a bit (like separate weakly supervised algos from supervised etc). I'll raise an issue for that

**Comment by perimosocordiae** [comment]
Merged, thanks! Moving the commented-out section should be handled by gh-149.

**Pull request merged**
